# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "博文"
  pageRef = "posts/"
  weight = 15

[[main]]
  name = "归档"
  pageRef = "archives/"
  weight = 20

[[main]]
  name = "标签"
  pageRef = "tags/"
  weight = 25

[[main]]
  name = "分类"
  pageRef = "categories/"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "about/"
  weight = 100

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

# [[main]]
#   identifier = "twitter"
#   pre = "x-twitter"
#   url = "https://x.com/dora_honor"
#   weight = 200

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Dora-Honor/mskk-hugo-blowfish"
  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "作者"
   pageRef = "about/"
   weight = 20
